### ISSUE TITLE
More distribution options

### ISSUE THREAD

**Issue by troycomi** [browning-lab/flare#1]
I'm interested in trying out flare.  Any chance you can make a docker image to simplify installation and versioning?

Can you make a release containing the jar through github as well?

I'm worried directly downloading the linked file won't be reproducible with new versions and compiling at a specific commit makes distribution difficult.

**Comment by thebigcorporation** [comment]
I am working on a docker file, but I am seeing the following build failures with Java 11 and Java 17 (both current LTS).

I was going to generate a PR with that docker file, but haven't had time to dig into this much deeper. If anyone has a quick fix, we can close on this.

Thanks

Sven

Step 12/17 : RUN javac -cp flare/src/ flare/src/admix/AdmixMain.java
 ---> Running in f32ea778c163
flare/src/admix/IbsHaps.java:36: error: unmappable character (0xE2) for encoding US-ASCII
 * <p>Reference: Durbin, R. 2014. Bioinformatics 30(9):1266???1272.
                                                           ^
flare/src/admix/IbsHaps.java:36: error: unmappable character (0x80) for encoding US-ASCII
 * <p>Reference: Durbin, R. 2014. Bioinformatics 30(9):1266???1272.
                                                            ^
flare/src/admix/IbsHaps.java:36: error: unmappable character (0x93) for encoding US-ASCII
 * <p>Reference: Durbin, R. 2014. Bioinformatics 30(9):1266???1272.
                                                             ^
3 errors

**Comment by thebigcorporation** [comment]
Please see:
https://github.com/browning-lab/flare/pull/5
