### ISSUE TITLE
Map file format error

### ISSUE THREAD

**Issue by hangsuUNC** [browning-lab/flare#11]
Dear Sir or Madam,

I was trying to run flare using a 1KGP reference panel. I had an error:
```
java.lang.IllegalArgumentException: Map file format error: pos chr cM
at vcf.PlinkGenMap.divideByChrom(PlinkGenMap.java:188)
at vcf.PlinkGenMap.fromPlinkMapFile(PlinkGenMap.java:117)
at vcf.GeneticMap.geneticMap(GeneticMap.java:119)
at admix.AdmixChromData$It.<init>(AdmixChromData.java:124)
at admix.AdmixMain.runAnalysis(AdmixMain.java:114)
at admix.AdmixMain.main(AdmixMain.java:68)
```

I download the b38 map files and the format is here:
```
pos     chr     cM
253938  19      0
256859  19      0.00045
259772  19      9e-04
260970  19      0.001086
261033  19      0.001095
266034  19      0.00187
266544  19      0.002047
266888  19      0.00248
267039  19      0.002681
267213  19      0.00295
267614  19      0.00382
269380  19      0.005779
276245  19      0.010664
```

I cannot tell why this map file doesn't work. I tried to gunzip the map file but still have the same error. Could you provide some suggestions how to resolve this issue?

Thank you so much,

Hang

**Comment by browning-lab** [comment]
Dear Hang Su,
The map file is not in PLINK's map format.  There should be a hyperlink on
the Beagle web page or in the Beagle documentation to the PLINK
documentation that specifies the map format.

Best regards,

Brian

**Comment by hangsuUNC** [comment]
Thank you so much! Found the correct files.

Best,

Hang
