### ISSUE TITLE
Run flare test

### ISSUE THREAD

**Issue by maryfdavis** [browning-lab/flare#15]
Hello,

I get this error when I try to run the test script for flare. Can you advise?

<img width="524" alt="Screenshot 2024-06-13 at 10 32 46 AM" src="https://github.com/browning-lab/flare/assets/172615562/1879ea70-fa90-4fad-9ee4-679f3ecfa8c8">

**Comment by browning-lab** [comment]
The error message suggests that the run.flare.test file on your computer
system is not the run.flare.test file on the GitHub website:

https://raw.githubusercontent.com/browning-lab/flare/master/test/run.flare.test
