### ISSUE TITLE
Running out of Java Heap space in one of two cohorts.

### ISSUE THREAD

**Issue by sinnweja** [browning-lab/flare#16]
I have a cohort of 4200 subjects that I was able to successfully run with 100G heap space on each chromosome in under 30 minutes each. Ancestry percentages match full-genome expected ancestry of about 60% EUR, 30% AMR, 10% mixed from 2 other ancestries.  I have a different ancestry cohort (mix of EUR+AFR) of 10K subjects that runs out of 400G of heap space on the smaller chromosomes. I used gt-samples option to only run flare on 3000 subjects. Still runs out of 400G of heap space. I pre-subset the sample vcf file to 1000 samples and no longer need gt-samples, and runs out of 250G of heap space.  Any idea what is causing the heap space to blow up on the second cohort?

**Comment by browning-lab** [comment]
Based on the information in your email, I don't know why you are seeing
this difference in memory use.   I assume that the number of ancestries in
the second analysis is less than or equal to the number of ancestries in
the first analysis.

If you partition the target samples and analyze them in separate analyses,
you can obtain the same results that you would have obtained by analyzing
all samples in a single analysis if you specify em=false and use the same
model, seed, and nthreads parameters for each analysis (see
https://github.com/browning-lab/flare?tab=readme-ov-file#running-flare-with-small-or-large-sample-sizes
).

**Comment by sinnweja** [comment]
Thank you for your reply. The number of ancestries for the second analysis I have tried with 2, 3, and 5 ancestries, with all those runs giving heap space errors.  We are familiar with running with the em=false and the model file, seed, etc, with great results. We had hoped to let flare estimate the ancestries independently on each chromosome, but we are fine using the model file with the ancestries provided from the overall estimates. I will be sure to use sufficiently large random partitions of the cohort, because some small subsets may not match the overall cohort ancestral mixture that we specify in the model file.

-Jason

**Comment by sinnweja** [comment]
Turns out my problems were caused by having the ref-panel file specified incorrectly. I was effectively having flare estimate many more than 5 ancestries. It is running fine now on all 10K subjects in cohort 2, with 5 ancestries.  I apologize for the confusion!

**Comment by browning-lab** [comment]
No problem.  I'm glad the problem is solved.  Thank you for letting me know.
