### ISSUE TITLE
Genetic Map File Choice

### ISSUE THREAD

**Issue by nick338** [browning-lab/flare#17]
Hello,

I was curious if you had any suggestions for choosing an appropriate genetic map file to use in a flare analysis, and if there were any criteria you had used to choose the Hap Map genetic map files that are linked here?

Thanks,
Nick

**Comment by browning-lab** [comment]
We include the HapMap genetic map because it is a good map that has been widely used.  If you wish, you can run test analyses with different genetic maps, and then use whatever genetic maps produces the most accurate results in your tests.
