### ISSUE TITLE
Convert FLARE to GDS file for use in GENESIS

### ISSUE THREAD

**Issue by qyang10** [browning-lab/flare#18]
Hi,
We are trying to use output from FLARE to perform admixture mapping using admixMap() in GENESIS.
Could you offer a suggestion on on how to split the FLARE output, a VCF file with ancestry probabilities, in our case ANP1:ANP2 of 5 ancestries to 5 ancestry specific files, each with ancestry probabilities for a single ancestry?
Or any other way to reformat FLARE output in order to use admixMap()?
Thanks so much! Sorry to ask something that is not an issue of your program at all.
Qiong

**Comment by browning-lab** [comment]
Dear Qiong,
I am not familiar with the format required by admixMap().  When I need to
manipulate the data in a VCF file,  Linux command line utilities are
usually sufficient to accomplish the task.  The zcat, cut, tr, and sed
Linux utilities are useful for manipulating VCF data.

Best regards,

Brian

**Comment by qyang10** [comment]
Thanks so much for the quick answer Brian! Thank for sharing your experience that simple Linux command line can accomplish the task of manipulating VCF data. 
Best,
Qiong
