### ISSUE TITLE
Discrodance between the Global Ancestry estimates using FLARE and ADMIXTURE and large estimate of Admixture time

### ISSUE THREAD

**Issue by Devashish13** [browning-lab/flare#4]
Hi,
[ABM_Flare_g70.out.log](https://github.com/browning-lab/flare/files/9436745/ABM_Flare_g70.out.log)
[ABM_Flare.out.log](https://github.com/browning-lab/flare/files/9436746/ABM_Flare.out.log)

I started implementing FLARE in Admixed Indian Subpopulations. Indian Populations are a result of complex admixture history of four ancestral populations Indo-European(IE), AustroAsiatic(AA), Dravidian(DR), Tibet-Berman(TB) speakers. The time since last admixture is around 70 generations as populations started endogamy.

By taking representative population for each of the four ancestral populations(having global ancestry~1) based on ADMIXTURE results and taking the Admixed populations data I am running FLARE.

Chromosome 21 has been taken to perform the analysis.

################## **FLARE output** #####################################
**Model 1: Default Parameters**

**list of ancestries**
IE      DR      AA      TB

**list of reference panels**
IE      DR      AA      TB

**T: number of generations since admixture**
1163.9318

**mu[i]: proportion of target genotypes with ancestry i**
1.0     0.0     0.0     0.0

**p[i][j]: probability that a model state haplotype is in reference panel j when the model state ancestry is i**
0.52692056      0.16545793      0.16131613      0.14630541
0.1464599       0.6767872       0.10465198      0.07210092
0.14689372      0.11054649      0.64248073      0.10007905
0.21040414      0.12552024      0.1592307       0.5048449

 **theta[i][j]: probability that a model state haplotype and the target haplotype carry different alleles when the model state haplotype is in reference panel j and the model state ancestry is i**
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4

 **rho[i]: rate of the exponential IBD segment cM-length distribution when the most recent common ancestor precedes admixture and has ancestry i**
1257.5281       795.9301        783.3869        1147.2806

**Model 2: gen=70,**
**list of ancestries**
IE      DR      AA      TB

 **list of reference panels**
IE      DR      AA      TB

**T: number of generations since admixture**
910.75415

 **mu[i]: proportion of target genotypes with ancestry i**
1.0     0.0     0.0     0.0

**p[i][j]: probability that a model state haplotype is in reference panel j when the model state ancestry is i**
0.52692056      0.16545793      0.16131613      0.14630541
0.1464599       0.6767872       0.10465198      0.07210092
0.14689372      0.11054649      0.64248073      0.10007905
0.21040414      0.12552024      0.1592307       0.5048449

**theta[i][j]: probability that a model state haplotype and the target haplotype carry different alleles when the model state haplotype is in reference panel j and the model state ancestry is i**
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4
9.54659E-4      9.54659E-4      9.54659E-4      9.54659E-4

**rho[i]: rate of the exponential IBD segment cM-length distribution when the most recent common ancestor precedes admixture and has ancestry i**
1257.5281       795.9301        783.3869        1147.2806

############## **ADMIXTURE Global Ancestry** for Admixed population taken under study

 Ancestral_pop                  IE               DR                  TB             AA
Global Ancestry                0.26           0.3                  0.18         0.26

I have also attached **log files** for your reference.

Please help me in understanding what is getting wrong here.

Thanks,
Devashish Tripathi

**Comment by browning-lab** [comment]
Dear Devanish,
Please send analysis related questions to Sharon ***@***.***).  Sharon
does not monitor this GitHub page.

Please include the log file and output .model file from your analysis as
e-mail attachments.

Thanks,

Brian Browning
