### ISSUE TITLE
Feature Request: Support for Additional Reference File Extensions

### ISSUE THREAD

**Issue by kscott-1** [browning-lab/flare#8]
Hi Dr. Browning, this request pertains to Beagle as well, but I thought this was the best place to start to put this out there.

As it stands, Beagle and Flare can accept .vcf, .vcf.gz & .bref3 as reference file input :

```
WARNING: unrecognized reference file type (expected ".bref3", ".vcf", or ".vcf.gz")

Exception in thread "main" java.lang.IllegalArgumentException: VCF record format error: 
	at vcf.VcfRecGTParser.ninthTabPos(VcfRecGTParser.java:87)
	at vcf.VcfHeader.isDiploid(VcfHeader.java:73)
	at vcf.RefIt.<init>(RefIt.java:130)
	at vcf.RefIt.create(RefIt.java:97)
	at vcf.RefTargSlidingWindow.refIt(RefTargSlidingWindow.java:122)
	at vcf.RefTargSlidingWindow.<init>(RefTargSlidingWindow.java:81)
	at vcf.RefTargSlidingWindow.instance(RefTargSlidingWindow.java:70)
	at main.Main.slidingWindow(Main.java:129)
	at main.Main.main(Main.java:107)
```

The official gnomAD bucket contains phased hgdp+1kg files in .bcf format & attempting to use those resulted in the above error. 

File Type :
`hgdp1kgp_chr22.filtered.SNV_INDEL.phased.shapeit5.bcf:      BCF version 2.2 compressed variant calling data`

There are also instances of .vcf.bgz files which cause the same errors. In the case of .gz and .bgz, bgzipped files are compliant with gzip, so the programs should also be able to accept .vcf.bgz files without changing any file reading logic as evidenced by bgzipped files with the .gz extension already working (most .vcf.gz files are already bgzipped, it is the standard in htslib).

Is this something that could be implemented?

Thanks for considering,
Kyle

**Comment by browning-lab** [comment]
Hi Kyle,
Thank you for your feedback.

The latest version of flare allows a gzip-compressed file to have a ".bgz
file extension.  Beagle currently requires bgzip-compressed files to have a
".gz" file extension, but the next update to Beagle will also allow the
".bgz" file extension.  In the meantime, changing the file extension from
".bgz" to ".gz" should provide a work around.  If this doesn't fix
the problem, please let me know.

Adding support for .bcf files is something I would like to do, but I don't
know when I will have time to do this.

Brian

**Comment by kscott-1** [comment]
I appreciate the quick response. The workaround for .bgz -> .gz does work and it's how I've used Beagle in those situations in the past. I will leave this open, but feel free to close it.
